export const userKey = {
  createdSuccess: 'user-created-success',
  updatedSuccess: 'user-updated-success',
  deletedSuccess: 'user-deleted-success',
  required: 'user-required',
  repeatedEmail: 'repeated-email',
  notFound: 'user-not-found',
  notVerified: 'not-verified',
  nicknameRequired: 'nickname-required',
  repeatedNickname: 'repeated-nickname',
}

export const mediaKey = {
  createMediaSuccess: 'media-created-success',
  createMediaError: 'media-created-error',
  deleteMediaSuccess: 'media-deleted-success',
  apiKeyNotFound: 'api-key-not-found',
  mediaNotExists: 'media-not-exists',
  mediaProtected: 'media-protected',
  mediaRequired: 'media-required',
  mediaDontBelongToLicense: 'media-dont-belong-to-license',
  getMediaSuccess: 'media-get-success',
  mediaNotFound: 'media-not-found',
}

export const licenseKey = {
  projectRequired: 'project-required',
  createdSuccess: 'license-created-success',
  repeatedProject: 'repeated-project',
  repeatedLicense: 'repeated-license',
  createDirectoryError: 'create-directory-error',
  createLicenseError: 'create-license-error',
  getLicenseSuccess: 'get-license-success',
  getApiKeySuccess: 'get-api-key-success',
  getMediaTokenSuccess: 'get-token-success',
  getLicenseError: 'get-license-error',
  licenseNotFound: 'license-not-found',
  apiKeyNotFound: 'api-key-not-found',
  mediaTokenNotFound: 'media-token-not-found',
  licenseNotEnabled: 'license-not-enabled',
  licenseOffline: 'license-offline',
  licenseOverMaxSize: 'license-over-max-size',
  licenseExpired: 'license-expired',
  licenseIdRequired: 'license-id-required',
  userLicenseError: 'user-license-error',
  createApiKeyTokenError: 'create-api-key-token-error',
  enabledRequired: 'enabled-required',
  onlineRequired: 'online-required',
  enableLicenseSuccess: 'enable-license-success',
  disableLicenseSuccess: 'disable-license-success',
  disableOnlineSuccess: 'disable-online-success',
  enableOnlineSuccess: 'enable-online-success',
  updateLicenseSuccess: 'update-license-success',
  deleteLicenseSuccess: 'delete-license-success',
  licenseOverMaxRequests: 'license-over-max-requests',
  freeLicensesLimit: 'free-licenses-limit',
}

export const subscriptionKey = {
  subscriptionNotFound: 'subscription-not-found',
  createSubscriptionError: 'create-subscription-error',
  subscriptionIdRequired: 'subscription-id-required',
  subscriptionDataRequired: 'subscription-data-required',
  subscriptionTypeInvalid: 'subscription-type-not-valid',
  subscriptionPriceInvalid: 'subscription-price-number-required',
  subscriptionCurrencyInvalid: 'subscription-currency-string-required',
  subscriptionMaxSizeInvalid: 'subscription-maxSize-number-required',
  subscriptionExpireInvalid: 'subscription-expire-string-required',
  subscriptionEnableInvalid: 'subscription-enable-boolean-required',
  subscriptionUpdatedSuccess: 'subscription-updated-success',
  subscriptionServerError: 'subscription-server-error',
  subscriptionNotAllowed: 'subscription-update-not-allowed',
}

export const responseKey = {
  serverError: 'server-error',
  notAllowed: 'not-allowed',
  roleNotAllowed: 'role-not-allowed',
  unauthorized: 'unauthorized',
  tokenExpired: 'token-expired',
  tokenInvalid: 'token-invalid',
  tokenNotFound: 'token-not-found',
}